board/urls.py
from django.urls import path, include
from .views import post_write, post_list, post_detail, post_delete, post_update, post_likes, \
    post_dislikes, reply_likes, reply_dislikes, reply_delete, reply_update, post_search, check_img

app_name = 'board'

urlpatterns = [
    path('<board_type>', post_list, name='board'),
    path('board/<board_type>/search', post_search, name='post_search'),
    path('board_write/<board_type>', post_write, name='board_write'),
    path('board_detail/<int:pk>', post_detail, name='post_detail'),
    path('board_detail/<int:pk>/delete', post_delete, name='post_delete'),
    path('board_detail/<int:pk>/modify', post_update, name='post_update'),
    path('board_detail/<int:pk>/post_likes/', post_likes, name='post_likes'),
    path('board_detail/<int:pk>/post_dislikes/', post_dislikes, name='post_dislikes'),
    path('board_detail/<int:pk>/reply_delete/<int:id>', reply_delete, name='post_delete'),
    path('board_detail/<int:pk>/reply_update/<int:id>', reply_update, name='post_delete'),
    path('board_detail/<int:pk>/reply_likes/', reply_likes, name='reply_likes'),
    path('board_detail/<int:pk>/reply_dislikes/', reply_dislikes, name='reply_dislikes'),
    path('board_write/api/check-img/', check_img, name='check_value'),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from public_function.public_func import handler403, handler500, handler400, handler404
from public_function.decorator import block_ip


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('politic/', include('politic_info.urls')),
    path('board/', include('board.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('main_page.urls')),
    path('robots.txt',  TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    # path('/$', block_ip(), 'name_of_view'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = handler403
handler404 = handler404
handler500 = handler500
handler400 = handler400

board/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator

from accounts.models import User


class Board(models.Model):
    board_id = models.CharField(max_length=20, null=False, verbose_name='게시판 종류')
    post_title = models.CharField(max_length=255, null=False)
    post_content = models.TextField(verbose_name='내용')
    post_like = models.ManyToManyField(User, related_name='post_likes', blank=True, db_column='user_id')
    post_dislike = models.ManyToManyField(User, related_name='post_dislikes', blank=True, db_column='user_id')
    post_writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='post_writer', verbose_name="작성자", null=True, db_column='user_id')
    post_create = models.DateTimeField(auto_now_add=True, verbose_name="작성일")
    post_update = models.DateTimeField(null=True, blank=True, verbose_name="수정일")
    post_views = models.PositiveIntegerField(default=0, verbose_name='조회수') # 0보다 크거나 같은 정수를 저장하는 필드

    def __str__(self):
        return self.post_title

    class Meta:
        db_table = 'board'

    def get_absolute_url(self):
        return reverse('board:id', args=[self.board_id, self.id])


class Reply(models.Model):
    reply_post = models.ForeignKey(Board, on_delete=models.CASCADE, default='')
    reply_contents = models.TextField(max_length=1000, null=False)
    reply_like = models.ManyToManyField(User, related_name='reply_likes', blank=True, db_column='user_id')
    reply_dislike = models.ManyToManyField(User, related_name='reply_dislikes', blank=True, db_column='user_id')
    reply_writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reply_writer', default='', db_column='user_id')
    reply_parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True) #대댓글

    reply_create = models.DateTimeField(auto_now_add=True, verbose_name="작성일")
    reply_update = models.DateTimeField(null=True, blank=True, verbose_name="수정일")

    class Meta:
        db_table = 'board_reply'


class ReplyCascade(models.Model): # many to many field는 ondelete가 없어서 이렇게 지정해야함.
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    reply_writer = models.ForeignKey(User, on_delete=models.CASCADE, db_column='user_id')


class Report(models.Model):
    report_post = models.ForeignKey(Board, on_delete=models.CASCADE, null=True, blank=True, default='')
    report_reply = models.ForeignKey(Reply, on_delete=models.CASCADE, null=True, blank=True, default='')
    report_user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, db_column='user_id')
    report_reason = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], null=False)
    report_create = models.DateTimeField(auto_now_add=True, verbose_name="등록일")

    class Meta:
        db_table = 'report'

board/forms.py
from django import forms
from .models import Board

from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget


class BoardWriteForm(forms.ModelForm):
    post_title = forms.CharField(
        label='글 제목',
        widget=forms.TextInput(
            attrs={
                'placeholder': '게시글 제목'
            }
        ),
        required=True,
    )
    post_content = SummernoteTextField()

    field_order = [
        'post_title',
        'post_content',
    ]

    class Meta:
        model = Board
        fields = [
            'post_title',
            'post_content',
        ]

        widgets = {
            'post_content':SummernoteWidget(),
        }

    def clean(self):
        cleaned_data = super().clean()

        post_title = cleaned_data.get('post_title', '')
        post_content = cleaned_data.get('post_content', '')

        if post_title == '':
            self.add_error('post_title', '글 제목을 입력하세요.')
        elif post_content == '':
            self.add_error('post_content', '글 내용을 입력하세요.')
        else:
            self.post_title = post_title
            self.post_content = post_content

board/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from django.db.models import Q, F, Count
from django.http import JsonResponse
from django.contrib import messages
from django.utils import timezone

from .forms import BoardWriteForm
from .models import Board, Reply, Report
from accounts.models import User
from public_function.public_func import paginator_func, divide_board, delete_img_s3
from public_function.decorator import block_ip
from public_function.public_data import BLOCK_TIME, IP
from public_function.decorator import login_required

from ratelimit.decorators import ratelimit
from datetime import timedelta

import json
import datetime


# 게시판 검색 함수
@block_ip
@ratelimit(key=IP, rate=BLOCK_TIME, block=True)
def search_list(request, categories, keyword): # 검색 결과 함수
    if keyword: # 키워드가 있다면
        question_list = categories.filter(
            Q(poli_nm__icontains=keyword)
        ).distinct() # 키워드에 대한 검색 결과 poli_nm이 포함된 키워드
        politic_list = paginator_func(request, question_list)
        if len(politic_list) == 0:
            message = keyword + '로 검색된 결과가 없습니다.'
        else:
            message = keyword + ' 검색 결과입니다.'
        poli_info = {
            'politic_list': politic_list,
            'message': message,
        }
    else: # 키워드가 없다면
        message = '검색어를 입력해주세요'
        poli_info = {
            'message': message,
        }

    return poli_info


# 게시글 리스트
@block_ip
@ratelimit(key=IP, rate=BLOCK_TIME, block=True)
def post_list(request, board_type=None):
    if request.method == 'GET':
        board_data = Board.objects.filter(board_id=board_type).order_by('post_create').annotate(reply_count=Count(F('reply')))[::-1] # 역참조로 댓글 갯수 확인
        board_data = paginator_func(request, board_data, 20)
        board_type_kr = divide_board(board_type, True)

        best_data = Board.objects.filter(board_id=board_type).filter(post_create__gte=timezone.localtime() - timedelta(days=7)).annotate(num_like=Count('post_like')).filter(num_like__gte=10).order_by('-num_like')[:5]
        if best_data:
            best_data = reversed(best_data.annotate(reply_count=Count(F('reply')))[::-1])

        return render(request, 'board/board.html', {'board_data': board_data, 'board_type':board_type_kr, 'board_type_en':board_type, 'best_post': best_data})


# 게시글 내 검색
@block_ip
@ratelimit(key=IP, rate=BLOCK_TIME, block=True)
def post_search(request, board_type=None): # 게시판 검색
    keyword = request.GET.get('search')
    choice = request.GET.get('choice')

    board_data = Board.objects.filter(board_id=board_type)
    if choice == 'title_content':
        board_data = board_data.filter(Q(post_title__icontains=keyword) | Q(post_content__icontains=keyword)).annotate(
            reply_count=Count(F('reply')))[::-1]
    elif choice == 'title':
        board_data = board_data.filter(Q(post_title__icontains=keyword)).annotate(
            reply_count=Count(F('reply')))[::-1]
    elif choice == 'content':
        board_data = board_data.filter(Q(post_content__icontains=keyword)).annotate(
            reply_count=Count(F('reply')))[::-1]
    elif choice == 'writer':
        board_data = board_data.filter(Q(post_writer__nickname__icontains=keyword)).annotate(
            reply_count=Count(F('reply')))[::-1]
    board_data = paginator_func(request, board_data, 10)
    board_type_kr = divide_board(board_type, True)
    return render(request, 'board/board.html',
                  {'board_data': board_data, 'board_type': board_type_kr,
                   'board_type_en': board_type, 'search': keyword, 'choice':choice})


# 게시글 쓰기 board_type은 게시판 졸유
@block_ip
@login_required
@ratelimit(key=IP, rate=BLOCK_TIME, block=True)
def post_write(request, board_type=None):
    session = request.session.get('authUser')
    context = {'login_session': session['nickname']}

    login_session = session['like']

    if login_session == '중도' and board_type[0:3] == 'opp' or login_session == '중도' and board_type[0:3] == 'rul': # 글쓰기 권한 나누기
        messages.warning(request, '글쓰기 권한이 존재하지 않습니다.')
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found')) # 이전페이지로 이동
    elif login_session == '진보' and board_type[0:3] == 'rul':
        messages.warning(request, '글쓰기 권한이 존재하지 않습니다.')
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
    elif login_session == '보수' and board_type[0:3] == 'opp':
        messages.warning(request, '글쓰기 권한이 존재하지 않습니다.')
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

    if request.method == 'GET':
        write_form = BoardWriteForm()
        context['forms'] = write_form
        board_type = divide_board(board_type, True)
        not_board_type = divide_board(board_type, False)
        context['board_type'] = board_type
        context['not_board_type'] = not_board_type

        return render(request, 'board/board_write.html', context)

    elif request.method == 'POST':
        write_form = BoardWriteForm(request.POST)

        if write_form.is_valid():
            writer = User.objects.get(nickname=session['nickname'])
            board = Board(
                post_title=write_form.post_title,
                post_content=write_form.post_content,
                post_writer=writer,
                board_id=board_type,
            )
            board.save()
            return redirect('board:board', board_type)
        else:
            context['forms'] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'board/board_write.html', context)


# 게시글 취소시 이미지 체크
def check_img(request):
    html_code = request.POST.dict()
    delete_img_s3([html_code['code']]) # 리스트 형식으로 전달
    result = {
        'result': 'success',
    }
    return JsonResponse(result)


# 게시글 업데이트
@block_ip
@login_required
@ratelimit(key=IP, rate=BLOCK_TIME, block=True)
def post_update(request, pk=None):
    session = request.session.get('authUser')
    context = {'login_session': session['nickname']}

    board = get_object_or_404(Board, id=pk)
    board_type = board.board_id
    context['board'] = board

    if board.post_writer.nickname != session['nickname']:
        return redirect(f'/board/board_detail/{pk}')

    if request.method == 'GET':
        write_form = BoardWriteForm(instance=board)
        context['forms'] = write_form
        board_type = divide_board(board_type, True)
        not_board_type = divide_board(board_type, False)
        context['board_type'] = board_type
        context['not_board_type'] = not_board_type
        return render(request, 'board/board_update.html', context)

    elif request.method == 'POST':
        write_form = BoardWriteForm(request.POST)
        now = datetime.datetime.now()
        time = now.strftime('%Y-%m-%d %H:%M:%S')
        if write_form.is_valid():
            board.post_title = write_form.post_title
            board.post_content = write_form.post_content
            board.board_id = board_type
            board.post_update = time # 댓글 수정시
            board.save()
            return redirect('board:board', board_type)
        else:
            context['forms'] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'board/board_write.html', context)


# 게시글 세부 내용
@block_ip
@ratelimit(key=IP, rate=BLOCK_TIME, block=True)
def post_detail(request, pk):
    board = get_object_or_404(Board, id=pk)
    re_replys = Reply.objects.filter(reply_post=pk, reply_parent__isnull=False)
    board_type = divide_board(board.board_id, True)  # 게시판 정보 한글

    context = {'detail':board}

    context['board_type'] = board_type
    if request.GET.get('search'):
        context['redirect'] = f'{request.GET.get("next")}&choice={request.GET.get("choice")}&search={request.GET.get("search")}'
    else:
        context['redirect'] = request.GET.get('next')

    best_reply = Reply.objects.filter(reply_post=pk).annotate(num_like=Count('reply_like')).filter(num_like__gte=10).order_by('-num_like')[:3]
    context['best_reply'] = best_reply

    if request.method == 'GET':
        reply = Reply.objects.filter(reply_post=pk, reply_parent__isnull=True)

        re_reply_list = list()
        for re_reply in re_replys:
            re_reply_list.append(re_reply.reply_parent.id)

        reply_count = len(reply) + len(re_replys)
        reply_pag = paginator_func(request, reply, 5)  # 댓글 페이지
        context['re_reply_list'] = re_reply_list
        context['reply_count'] = reply_count
        context['re_reply'] = re_replys
        context['reply'] = reply_pag

        board.post_views += 1  # 조회수 클릭당 1
        board.save()
        if request.session.get('authUser'):
            session = request.session.get('authUser')['nickname']
            context['login_session'] = session
            try:
                if board.post_writer.nickname == session:  # 글쓴 유저가 같으면 수정, 삭제버튼 보이게
                    context['writer'] = True
                else:
                    context['writer'] = False
            except:
                context['writer'] = False
            return render(request, 'board/board_detail.html', context)
        else:
            return render(request, 'board/board_detail.html', context)
    elif request.method == 'POST':
        if request.POST.get('choice'): # 댓글 정렬
            value = request.POST.get('choice')
            if value == 'new':
                reply = Reply.objects.filter(reply_post=pk, reply_parent__isnull=True)
            elif value == 'most_like':
                reply = Reply.objects.filter(reply_post=pk, reply_parent__isnull=True).annotate(num_like=Count('reply_like')).order_by('-num_like')
            elif value == 'most_dislike':

board/templates/board/board_update.html
{% extends 'base.html' %}

{% block title %}- 게시글 업데이트{% endblock %}

{% block color %}
    {% if board_type|slice:2 == '여당' %}
        #C55050;
    {% elif board_type|slice:2 == '자유' %}
        #4B4B4B;
    {% else %}
        #4543B8;
    {% endif %}
{% endblock %}

{% block script %}

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.js"></script>
<script type="text/javascript" src="/static/js/lang/summernote-ko-KR.js"></script>
<style>
    #write_list li{
        margin-bottom:20pt;
        margin-left:-20pt;
    }
</style>
{% endblock %}

{% block content %}
    <div style="margin:5pt;">
        <h5>게시판 글쓰기</h5>
        <div>저작권 등 다른 사람의 권리를 침해하거나 명예를 훼손하는 게시글은 관련 법률에 의해 제제를 받을 수 있습니다.</div>
        <hr width="820px;" color="black" size="5">
        <form action="" method="POST" style="margin-top:10pt;">
            {% csrf_token %}
            <ul style="list-style-type: none;" id="write_list">
                <li>
                    <label for="id_post_title" style="width:100pt;">제목</label>
                    <input type="text" name="post_title" id="id_post_title" style="width:250pt;" value="{{ forms.post_title.value | safe }}" placeholder="게시글 제목">
                </li>
                <li>
                    <label for="id_board_id" style="width:100pt;">게시판 종류</label>
                    <input name="board_id" id="id_board_id" value="{{ board_type }}" style="border:none;" disabled>
                </li>
                <li>
                    <label for="id_post_content">내용</label>
                    {{ forms.post_content }}
                </li>
            </ul>
            {% if error %}
                {{ error }}
            {% endif %}
            <button type="submit">수정</button>
            <input type="button" value="취소" onclick="history.go(-1)">
        </form>
    </div>
{% endblock %}

board/templates/board/board_write.html
{% extends 'base.html' %}

{% block title %}- 게시판 글쓰기{% endblock %}

{% block color %}
    {% if board_type|slice:2 == '여당' %}
        #C55050;
    {% elif board_type|slice:2 == '야당' %}
        #4543B8;
    {% else %}
        #4B4B4B;
    {% endif %}
{% endblock %}

{% block script %}
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.js"></script>
<script type="text/javascript" src="{% static 'summernote/lang/summernote-ko-KR.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/board_write.js' %}"></script>
<style>
    #write_list li{
        margin-bottom:20pt;
        margin-left:-20pt;
    }

    .button_submit{
        color:white;
        background-color:
        {% if board_type|slice:2 == '여당' %}
            #C55050;
        {% elif board_type|slice:2 == '야당' %}
            #4543B8;
        {% else %}
            #4B4B4B;
        {% endif %}
    }
</style>
{% endblock %}

{% block content %}
    <div style="margin:5pt;">
        <h5>게시판 글쓰기</h5>
        <div>저작권 등 다른 사람의 권리를 침해하거나 명예를 훼손하는 게시글은 관련 법률에 의해 제제를 받을 수 있습니다.</div>
        <hr width="820px;" color="black" size="5">
        <form action="" method="POST" style="margin-top:10pt;">
            {% csrf_token %}
            <ul style="list-style-type: none;" id="write_list">
                <li>
                    <label for="id_post_title" style="width:100pt;">제목</label>
                    <input type="text" name="post_title" required="" id="id_post_title" style="width:500pt;">
                    <span style="font-size:12pt; color:#aaa; float:right; color:black; margin-right:45pt;" class="counter">(0 / 최대 40자)</span>
                </li>
                <li>
                    <label for="id_board_id" style="width:100pt;">게시판 종류</label>
                    <input name="board_id" id="id_board_id" value="{{ board_type }}" style="border:none;" disabled>
                </li>
                <li>
                    <label for="id_post_content">내용</label>
                    {{ forms.post_content }}
                </li>
            </ul>
            {% if error %}
                {{ error }}
            {% endif %}
            <button class="button_submit" type="submit" onclick="insert()">등록</button>
            <input class="button_submit" id="cancel" type="button" name="test" value="취소">
        </form>
    </div>
{% endblock %}