accounts/urls.py
from django.urls import path
from .views import login, logout, register, check_value, register_terms, mypage, my_write, \
    my_reply, delete_account, send_email, check_number, find_account, find_pw

app_name = 'accounts'

urlpatterns = [
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
    path('register', register, name='register'),
    path('register-terms', register_terms, name='register_terms'),
    path('register/api/check-value/', check_value, name='check_value'),
    path('api/check-value/', check_value, name='check_value'),
    path('api/send-email/', send_email, name='send_email'),
    path('api/check-number/', check_number, name='send_email'),
    path('api/find-pw/', find_pw, name='find_pw'),
    path('mypage', mypage, name='mypage'),
    path('mypage/my-write', my_write, name='my_write'),
    path('mypage/my-reply', my_reply, name='my_reply'),
    path('mypage/leave-poty', delete_account, name='leave_poty'),
    path('mypage/api/check-value/', check_value, name='check_value'),
    path('find-account', find_account, name='find_account'),

]

board/urls.py
from django.urls import path, include
from .views import post_write, post_list, post_detail, post_delete, post_update, post_likes, \
    post_dislikes, reply_likes, reply_dislikes, reply_delete, reply_update, post_search, check_img

app_name = 'board'

urlpatterns = [
    path('<board_type>', post_list, name='board'),
    path('board/<board_type>/search', post_search, name='post_search'),
    path('board_write/<board_type>', post_write, name='board_write'),
    path('board_detail/<int:pk>', post_detail, name='post_detail'),
    path('board_detail/<int:pk>/delete', post_delete, name='post_delete'),
    path('board_detail/<int:pk>/modify', post_update, name='post_update'),
    path('board_detail/<int:pk>/post_likes/', post_likes, name='post_likes'),
    path('board_detail/<int:pk>/post_dislikes/', post_dislikes, name='post_dislikes'),
    path('board_detail/<int:pk>/reply_delete/<int:id>', reply_delete, name='post_delete'),
    path('board_detail/<int:pk>/reply_update/<int:id>', reply_update, name='post_delete'),
    path('board_detail/<int:pk>/reply_likes/', reply_likes, name='reply_likes'),
    path('board_detail/<int:pk>/reply_dislikes/', reply_dislikes, name='reply_dislikes'),
    path('board_write/api/check-img/', check_img, name='check_value'),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from public_function.public_func import handler403, handler500, handler400, handler404
from public_function.decorator import block_ip


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('politic/', include('politic_info.urls')),
    path('board/', include('board.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('main_page.urls')),
    path('robots.txt',  TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    # path('/$', block_ip(), 'name_of_view'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = handler403
handler404 = handler404
handler500 = handler500
handler400 = handler400

main_page/urls.py
from django.urls import path
from .views import *

app_name = 'main_page'

urlpatterns = [
    path('', main_page, name='main_page'),
    path('search', search_all, name='search'),
]

politic_info/urls.py
from django.urls import path

from .views import rul_politic_list, oppo_politic_list, politic_detail, check_value, likes\
    ,dislikes, delete


app_name = 'politic'

urlpatterns = [
    path('rul_politic_list', rul_politic_list, name='rul_politic_list'),
    path('oppo_politic_list', oppo_politic_list, name='oppo_politic_list'),
    path('<int:id>/<politic_slug>/', politic_detail, name='politic_detail'),
    path('<int:id>/<politic_slug>/api/check-value/', check_value, name='check-value'),
    path('<int:id>/<politic_slug>/like/', likes, name='likes'),
    path('<int:id>/<politic_slug>/dislike/', dislikes, name='dislikes'),
    path('<int:id>/<politic_slug>/<int:pk>/delete', delete, name='dislikes'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Poty {% block title %}{% endblock %}</title>
<!--    <link rel="stylesheet" href="/static/css/base_style.css">-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}

</head>
<body>
{% if session_error %}
<ul class="messages">
    <script>alert("{{ session_error }}")</script>
</ul>
{% endif %}
    <h3 style="color:red; margin-left:20pt;">테스트 서버입니다. 회원가입을 해도 관련 정보는 모두 삭제됩니다.</h3>
    <div style="overflow:hidden; height:auto;">
        <div class="main-div">
            <div class="logo-container">
                <div class="">
                    <button type="button" id="img_btn" onclick="location.href='/'">
                        <img src="{% static 'media/logo/logo.png' %}" width="203" height="85">
                    </button>
                </div>
            </div>
<!--            메뉴바 색상 변경-->
            <div id="main_navbar">
                <nav class="navbar navbar-expand-lg" style="background-color:{% block color %}{% endblock %}
                    ">
                  <div class="container-fluid" style="position:relative">
                      <nav id="menu_bar">
                          <ul>
                            <li><a class="menu_btn" href="/board/rul_free">여당 게시판</a></li>
                            <li><a class="menu_btn" href="{% url 'politic:oppo_politic_list' %}">여당 정치인 정보</a></li>
                            <li><a class="menu_btn" href="/board/oppo_free">야당 게시판</a></li>
                            <li><a class="menu_btn" href="{% url 'politic:rul_politic_list' %}">야당 정치인 정보</a></li>
                            <li><a class="menu_btn" href="/board/free_free">자유게시판</a></li>
                              <li style="margin-left:200px;">
                                <form id="search_structure" method="get" action="{% url 'main_page:search' %}">
                                        <input id="search_box" name="search" type="search"  placeholder="검색어를 입력하세요." aria-label="Search">
                                        <button id="search_btn_img" type="submit" style="background-color: transparent; border:none;">
                                            <img src="{% static 'media/search.svg' %}" width="20" height="20">
                                        </button>
                                </form>
                              </li>
                          </ul>
                    </nav>
                  </div>
                </nav>
            </div>
        </div>
        <div id="base_structure" style="overflow:hidden; height:auto;">
            <div id="left_ads">
                <script src="https://ads-partners.coupang.com/g.js"></script>
                <script>
                    new PartnersCoupang.G({"id":591214,"template":"carousel","trackingCode":"AF1530473","width":"168","height":"678"});
                </script>
            </div>
            <div id="main_structure">
<!--                화면 중앙 모든 페이지에서 바뀌는 부분-->
                <div id="center_structure"  style="overflow:hidden; height:auto;">
                    {% block content %}
                    {% endblock %}
                </div>
<!--                로그인 및 회원 정보칸-->
                <div>
                    {% if request.session.authUser is None %}
                        <div id="user_box_login">
                            <center>
                                {% if detail %}
                                    <a id="logout_link" class="nav-link" href="{% url 'accounts:login' %}?next={{ request.path }}?next={{ request.GET.next }}">로그인</a>
                                {% else %}
                                    <a id="logout_link" class="nav-link" href="{% url 'accounts:login' %}?next={{ request.path }}">로그인</a>
                                {% endif %}
                            </center>
                        </div>
                    {% else %}
                        <div id="user_box">
                            <div style="margin-top:5px;margin-left:5px;">
                                <ul id="user_box_ul">
                                    <li style="margin-left:-30px;float:left;">
                                        <span style="font-size:50pt; color:
                                            {% if request.session.authUser.like == '진보' %}
                                                blue;
                                            {% elif request.session.authUser.like == '보수' %}
                                                red;
                                            {% else %]
                                                black;
                                            {% endif %}
                                            ">Ⅸ</span>
                                    </li>
                                    <li style="margin-left:30px;">
                                        <span><a style="font-size:13px; display:block; font-weight:bolder;" id="nickname">{{ request.session.authUser.nickname }}님</a></span>
                                        <span><a style="font-size:13px; display:block;">정치성향: {{ request.session.authUser.like }}</a></span>
                                        <span><a style="font-size:13px; display:block;">급수: 준비중 </a></span>
                                        <span><a style="font-size:13px; display:block;">Exp: 준비중</a></span>
                                    </li>
                                </ul>
                            </div>
                            <div style="margin-top:-10px; margin-left:70px;">
                                <a class="button" href="{% url 'accounts:mypage' %}" style="font-size:12px; text-decoration-line:none; color:black; float:left;">마이페이지</a>
                                {% if detail %}
                                    <a class="button" href="{% url 'accounts:logout' %}?next={{ request.path }}?next={{ request.GET.next }}" style="margin-left:4pt; float:left; font-size:12px; text-decoration-line:none; color:black;">로그아웃</a>
                                {% else %}
                                    <a class="button" href="{% url 'accounts:logout' %}?next={{ request.path }}" style="margin-left:4pt; float:left; font-size:12px; text-decoration-line:none; color:black;">로그아웃</a>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                </div>
<!--                오른쪽 광고 위치-->
                <div id="right_ads">
                    <script src="https://ads-partners.coupang.com/g.js"></script>
                    <script>
                        new PartnersCoupang.G({"id":591220,"template":"carousel","trackingCode":"AF1530473","width":"188","height":"678"});
                    </script>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div id="footer_info">
            <ul>
                <li>문의, 버그, 개선 신고: policmty@gmail.com</li>
                <li>사이트 이용 관련: <a href="/board/notice">공지사항</a></li>
                <li>파트너스 활동을 통해 일정액의 수수료를 제공받을 수 있음</li>
            </ul>
        </div>
        </div>
</body>

</html>

templates/mypage.html
{% extends 'base.html' %}
{% block title %}- 마이페이지{% endblock %}
{% block color %}
    {% if request.session.authUser.like == '진보' %}
        #4543B8;
    {% elif request.session.authUser.like == '보수' %}
        #C55050;
    {% else %}
        #4B4B4B;
    {% endif %}
{% endblock %}

{% load static %}

{% block script %}

{% endblock %}

{% block content %}
    {% if session_error %}
        <ul class="messages">
            <script>alert("{{ session_error }}")</script>
        <!--    로그인 상태일때 로그인 혹은 회원가입을 시도하면-->
        </ul>
    {% endif %}
    <div style="margin:5pt;">
        <h5>마이페이지</h5>
        <div style="margin:5pt;">
            <div style="float:left;">
                <ul style="background-color:gray; color:white; list-style-type:none; width: 90pt; height: 200pt; padding-left:5pt; padding-top:10pt;">
                    <li style="margin: 5px;">
                        <a class="menu" href="/accounts/mypage">기본정보</a>
                    </li>
                    <li style="margin: 5px;">
                        <a class="menu" href="/accounts/mypage/my-write">내가 쓴 글</a>
                    </li>
                    <li style="margin: 5px;">
                        <a class="menu" href="/accounts/mypage/my-reply">내가 쓴 댓글</a>
                    </li>
                    <li style="margin: 5px;">
                        <a class="menu" href="/accounts/mypage/leave-poty">회원탈퇴</a>
                    </li>
                </ul>
            </div>
            <div style="float:left; width:500pt; margin-left:10pt;margin-top:10px;">
                {% block mypage_content %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/politic_list.html
{% extends 'base.html' %}
{% block title %}- 정치인 리스트{% endblock %}
{% block script %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/politic_list_style.css' %}">
    <style>{% block btn_color %}{% endblock %}</style>
{% endblock %}
{% block content %}
{% load mathfilters %}
<div style="margin: 5pt;">
    <div><h4><b>{% block info %} {% endblock %}</b></h4></div>
    <div style="float:left">이미지를 클릭하면 상세정보 및 별점을 매길 수 있습니다.</div>
    <form id="search_structure" method="post" style="float:right;">
        {%csrf_token %}
        <input id="search_box" name="keyword" type="search" placeholder="검색어를 입력하세요." aria-label="Search">
        <button id="search_btn_img" type="submit" style="border:none; background-color:transparent;">
            <img src="{% static 'media/search2.svg' %}" width="20" height="20">
        </button>
    </form>
    {% if message %}
        <br>
        <div>{{message}}</div>
    {% endif %}
    <div id="main_politic_structure">
        <div id="top_politic_structure">
            <h5 style="float:left;">{% block position %} {% endblock %}</h5>
        </div>
        <br>
        <div style="margin-left:15pt;">
            {% if politic_list %}
                {% for c in politic_list %}
                            <div class="politic_img">
                                <a href="{{ c.list.get_absolute_url }}">
                                    <img src="https://poty.s3.ap-northeast-2.amazonaws.com/static/politic/{{ c.list.poli_nm }}.jpg" width="140" height="180">
                                </a>
                                <br>
                                <div class="star-ratings">
                                    <div class="star-ratings-fill space-x-2 text-lg" style="width:{% if not c.avg.rate__avg %}0{% else %}{{ c.avg.rate__avg | mul:20}}{% endif %}%">
                                        <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                                    </div>
                                    <div class="star-ratings-base space-x-2 text-lg">
                                        <span>★</span><span>★</span><span>★</span><span>★</span><span>★</span>
                                    </div>
                                </div>
                                <a id="avg_rate">({% if not c.avg.rate__avg %}0.0{% else %}{{ c.avg.rate__avg }}{% endif %})</a>
                                <br>
                                    <div id="politic_nm">{{ c.list.poli_nm }}</div>
                            </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div id="pagination_structure">
            <div class="pagination">
                <div style="margin: 5px;">
                {% if politic_list.has_previous %}
                    <a class="abutton" href="?page=1">처음</a>
                    <a class="abutton" href="?page={{ politic_list.previous_page_number }}">이전</a>
                {% endif %}
                </div>

                <div style="margin: 5px;">
                {% for page in politic_list.paginator.page_range %}
                    {% if page >= politic_list.number|add:-2 and page <= politic_list.number|add:2 %}
                    <span class="{% if page == politic_list.number %}current{% else %}base{% endif %}">
                        <a href="?page={{ page }}" class="{% if page == politic_list.number %}current{% else %}base{% endif %}">{{ page }}</a>
                    </span>
                    {% elif page >= politic_list.number|add:-3 and page <= politic_list.number|add:3 %}
                        ..
                    {% endif %}
                {% endfor %}
                </div>

                <div style="margin: 5px;">
                {% if politic_list.has_next %}
                    <a class="abutton" href="?page={{ politic_list.next_page_number }}">다음</a>
                    <a class="abutton" href="?page={{ politic_list.paginator.num_pages }}">끝</a>
                {% endif %}
                </div>

            </div>
        </div>
</div>
{% endblock %}